# use new docker environment
sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - git
      - libc6-i386
      - g++-5
      - gcc-5
      - cppcheck

# We use cpp for unit tests, and c for the main project.
language: cpp
compiler:
      - gcc

before_install:
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90
    - curl --retry 10 --retry-max-time 120 -L "https://launchpad.net/gcc-arm-embedded/5.0/5-2015-q4-major/+download/gcc-arm-none-eabi-5_2-2015q4-20151219-linux.tar.bz2" | tar xfj -

install:
  - export PATH=$PATH:$PWD/gcc-arm-none-eabi-5_2-2015q4/bin

before_script: 
        - arm-none-eabi-gcc --version
        - gcc --version

script: 
        - ./configure
        - make test 
        - make clean 
